### ISSUE TITLE
access token gets rejected after password change

### ISSUE THREAD

**Issue by crslp** [vinkla/instagram#103]
For six months, I use this package with no issues.
Today, I changed my instagram password and recieved a new access token for the API via https://www.instagram.com/developer/authentication/

After changing the INSTAGRAM_ACCESS_TOKEN in the .env, I cleared all (known) caches:

composer dump-autoload
artisan cache:clear

but I still get an InstagramException: The access_token provided is invalid.

As a last step I deleted files bootstrap/cache. Still no success.

What do I miss?

**Comment by vinkla** [comment]
Does it work if you set the `access_token` directly in your PHP code instead of in the `.env` file?
