### ISSUE TITLE
Trying to get property 'text' of non-object

### ISSUE THREAD

**Issue by Vicftz** [vinkla/instagram#109]
Hello,

Your package is perfect and all is working for me except one thing. I don't know, but when I fetch all media from my account, I've the following problem : 

`{{ $media->caption->text }}` is not working in my blade file (all other argument work), i got this : 
**Trying to get property 'text' of non-object**

But when i do `dd($media->caption->text);` in my controller, this is working ... (I got my string, this is so weird ..)

Thanks by advance!

**Comment by vinkla** [comment]
Hmm, if this is working in your controller but not in your Blade view it probably means this is an issue how you send the data from your controller to the view.
