### ISSUE TITLE
ACCESS TOKEN provided is invalid

### ISSUE THREAD

**Issue by JeanValJeann** [vinkla/instagram#111]
Hi there,

All was worked fine but yesterday I noticed I was getting an error from this package : 
`The access_token provided is invalid.`

I directly searched to find out where this error was coming from in Instagram side and saw that they remove all my registered clients using the Instagram API... It seems like they stopped it. They now are redirecting developper community to https://developers.facebook.com/docs/instagram-basic-display-api/ but this new one "Basic display API" looks like an entirely new one to implement.

Some one in here get any further informations ?

**Comment by vinkla** [comment]
Did you try to generate a new token?

http://instagram.pixelunion.net

**Comment by JeanValJeann** [comment]
It works!
So I didn't understand why Instagram API removed automatically my registered clients...
