### ISSUE TITLE
Vinkla\\Instagram\\Instagram::__construct() must implement interface

### ISSUE THREAD

**Issue by suchiavana** [vinkla/instagram#116]
### Scenario:
Once I call `Instagram()` class with the proper access token, it shows the following error-
__argument 1 passed to Vinkla\\Instagram\\Instagram::__construct() must implement interface GuzzleHttp\\ClientInterface or be null, string given__

### Reproduct
To reproduce the issue-

```
use Vinkla\Instagram\Instagram;

...
...

$instagram = new Instagram($request->access_token);
$userData = $instagram->self();

dd($userData);
```

**Comment by vinkla** [comment]
Try installing the package with its dependencies:

```sh
composer require vinkla/instagram php-http/message php-http/guzzle6-adapter
```
