### ISSUE TITLE
Lets create the community! 

### ISSUE THREAD

**Issue by ohld** [vinkla/instagram#117]
Hi! I'm the creator and main developer of https://github.com/instagrambot/instabot

Several largest Instagram-related Open Source projects were taken down recently. My project is the next most popular - I think it will be deleted soon tool. Maybe the same story would happen with your project too.

I think we need to unite our forces and create one big Instagram-relate community to support each other and develop more open-source tools. I already have one: it is located in Telegram. Here is the link: https://t.me/instabotproject. This is a channel (4k members) and a chat (3k members). There are some projects that are already with us, the most important - https://t.me/likemeupbot - 10k active users.

What do you think?

**Comment by vinkla** [comment]
Hi! Thanks for reaching out and for the invite. I've noticed Instagram is shutting down projects. I not sure they'll close down this project though. We still use their official API which will be closed down later this year. There are currently non plans to keep the project alive when that happens.

---

[This Video Has 7,707,876 Views](https://www.youtube.com/watch?v=BxV14h0kFs0) - Tom Scott
