### ISSUE TITLE
Update Cosenary Instagram-PHP-API version?

### ISSUE THREAD

**Issue by benhanks040888** [vinkla/instagram#12]
Right now, it's still ~2.0, while the master branch of Cosenary Instagram-PHP-API has some nice updates like `getRateLimit()`

**Comment by vinkla** [comment]
We're using the latest version of @cosenary's Instagram package already. `~2.0` means it will take all version up to `3.0`. The latest version of @cosenary's Instagram package is `2.3`.

**Comment by benhanks040888** [comment]
So the latest update in @cosenary's Instagram package master branch not included until he releases version 2.4 or 3.0?

**Comment by vinkla** [comment]
Yes, that is correct. Hopefully it will be soon since Instagram has updated their API recently.
