### ISSUE TITLE
Where is Request::get('code') coming from?

### ISSUE THREAD

**Issue by ayatojhans** [vinkla/instagram#13]
I might be severely overlooking something, because I don't see how do I get the $code. I'm trying to set up authentication.

The callback url I've set in the config file is the same as the one I have for the client.

All I get is `Undefined property: stdClass::$access_token`. I'm using the example provided in this repo. Who exactly is giving me the $code?

**Comment by vinkla** [comment]
@ayatojhans Please see the [example project](https://github.com/cosenary/Instagram-PHP-API/tree/master/example) in the [original package repository](https://github.com/cosenary/Instagram-PHP-API/tree/master/example).

**Comment by ayatojhans** [comment]
Where's the first URL the user must hit to register?

**Comment by ayatojhans** [comment]
Ok so, the user must first hit a route that redirects to $instagram->getLoginUrl()? And then Instragram will hit my callback url with said $code?

**Comment by vinkla** [comment]
@ayatojhans Yes, that is the correct flow. Then on the callback URL you can fetch the `$code` parameter and store it in a session.

**Comment by ayatojhans** [comment]
I see. Now, can I store the Instagram::getOAuthToken($code) into the cache to use it later? Does it expire?

**Comment by vinkla** [comment]
It will probably expire sometime. You should store it in a session and test if it is still valid. Otherwise do the same procedure again.

> Access tokens may expire at any time in the future - https://instagram.com/developer/authentication

**Comment by ayatojhans** [comment]
My goal is to have a page that displays my client's feed. Obviously, I don't want him constantly authenticating in order to show the feed.

Could you give me an example of how would you go about that?

**Comment by vinkla** [comment]
You only want to fetch a public feed?

**Comment by ayatojhans** [comment]
No, I need to use getUserFeed(). I'm interested in how would you store the token for future use, and how to verify if it's still valid.

**Comment by vinkla** [comment]
If the user feed you want to have is public for everyone you don't need to login him in. Then you can fetch  the user like this:

```php
$instagram->getUserMedia('theusername', 30);
```

This should work fine. I've done it myself in a couple of projects.

**Comment by ayatojhans** [comment]
Ohh there we go! Thanks very much :D

**Comment by vinkla** [comment]
Anytime!

**Comment by puzpuz** [comment]
Hi vinkla, I'm new to laravel, and I would like to try your Instagram wrapper and follow the above but I get this following error
>Call to a member function getTagMedia() on a non-object

this is the syntax that I used

    protected $instagram;
    public function _construct(InstagramManager $instagramManager) {
        $this->instagram = $instagramManager;
    }
    public function index() {
        $userId = 'sby.sweetrecipe';
        $result  = $this->instagram->getTagMedia($userId,30);
    }

Please help me, thank you
