### ISSUE TITLE
Undefined property: stdClass::$pagination

### ISSUE THREAD

**Issue by DeeJaVu** [vinkla/instagram#19]
i dont understand how i can do the pagination for getPopularMedia()

code of my controller is

    $popular = $this->instagram->getPopularMedia();
    $testp = $this->instagram->pagination($popular);

when i return $testp i get a Undefined property: stdClass::$pagination error

what am i doing wrong ?

**Comment by vinkla** [comment]
Please open an issue at the base package repository https://github.com/cosenary/Instagram-PHP-API/issues/new
