### ISSUE TITLE
How to auth with instagram?

### ISSUE THREAD

**Issue by imkevinabraham** [vinkla/instagram#20]
I've followed the instructions and using this to try and auth

        // Get code parameter.
        $code = $request->get('code');

        // Request the access token.
        $data = Instagram::getOAuthToken($code);

        // Set the access token with $data object.
        Instagram::setAccessToken($data);

        // We're done here - how easy was that, it just works!
        Instagram::getUserLikes();
        // This example is simple, and there are far more methods available.

But I keep getting an error 

        ErrorException in Instagram.php line 526:
        Undefined property: stdClass::$access_token

How do we auth a user to be able to get data from his/her profile?

**Comment by vinkla** [comment]
When did you create your Instagram application?

**Comment by imkevinabraham** [comment]
I created it maybe 10 mins before trying to auth. 

I figured out the problem was I needed to use instagram::getLoginUrl() and it worked was able to get the basic user details. 

As for Instagram::getUserLikes(); I believe I need to get my app reviewed before I can get anything more on the scope than basic.

**Comment by vinkla** [comment]
All new Instagram application created after the 17th Nov wont work with this package.

**Comment by vinkla** [comment]
Please see https://github.com/cosenary/Instagram-PHP-API/issues/182
