### ISSUE TITLE
New scopes

### ISSUE THREAD

**Issue by kotchuprik** [vinkla/instagram#21]
hi! can you look this pull request? :)
https://github.com/cosenary/Instagram-PHP-API/pull/186

this is very urgent bug, thanks!

**Comment by vinkla** [comment]
Hey, I'm not in charge of that package and can't make those kinds of decisions. Sorry.

**Comment by kotchuprik** [comment]
ohh. I saw your commits and was sure that you can do it :)

**Comment by vinkla** [comment]
I suggest you reach out the package maintainer.

**Comment by kotchuprik** [comment]
I think that the maintainer is on vacation. thank you :)
