### ISSUE TITLE
There is no way  for setting existing json access tokens.

### ISSUE THREAD

**Issue by Kabangi** [vinkla/instagram#26]
Can't use this because the access token is in json format and converting it to 'League\OAuth2\Client\Token\AccessToken' generates an error `Argument 1 passed to League\OAuth2\Client\Token\AccessToken::__construct() must be of the type array, null given,`
`Instagram::setAccessToken($token);`

**Comment by vinkla** [comment]
@hassankhan any input on this?

**Comment by hassankhan** [comment]
Erm, if you already have a token in JSON format, you should be able to easily decode it to an array using `json_decode($json, true)` and then pass it to the constructor.

**Comment by ssuhat** [comment]
+1 I experience this issue. I fill all the require id, secret, and access_token but still got that error.

**Comment by hassankhan** [comment]
Can you show a code example of what you did please? Thanks

**Comment by ssuhat** [comment]
@hassankhan I just simply return like at read.md

      return Instagram::users()->get(30);

**Comment by hassankhan** [comment]
Would it be possible to get a more complete code example?

**Comment by ssuhat** [comment]
@hassankhan That's the only code I have (other than plugin config). 
I just want to try that this plugin working first.

**Comment by jufy** [comment]
[ protected $instagram;

    public function __construct(InstagramManager $instagram)
    {
        $this->instagram = $instagram;
    }

 public function setToken($token)
    {
        $this->token = new AccessToken(['access_token' => $token]);
        $this->instagram->setAccessToken($this->token);
        return $this;
    }

 $media = $this->instagram->users()->getMedia();

](url)

**Comment by jufy** [comment]
Faced same issue

**Comment by Taytus** [comment]
I'm having the same issue.

**Comment by mbarwick83** [comment]
Same issue.

**Comment by hassanazimi** [comment]
Same issue here

**Comment by Xaxio** [comment]
I'm having the same issue.

**Comment by mbarwick83** [comment]
I created my own, very small/light package, that might help people experiencing problems. No where near perfect or complex, but relatively easy. Requires Guzzle 6 though. https://github.com/mbarwick83/instagram

**Comment by hassankhan** [comment]
Sorry guys, just don't have the time to maintain my PHP projects nowadays, if anyone's willing to take over [Elogram](https://github.com/larabros/elogram) or be a contributor, more than happy to add them.

Thanks 😄

**Comment by vinkla** [comment]
@hassankhan what happened? To much work?

**Comment by hassankhan** [comment]
I've been really ill (physically and mentally) and at work I don't get the chance to work on PHP at all (mainly Node/AWS management nowadays). I feel super-shit for keeping all you guys on the hook for so long, really sorry 😞

**Comment by vinkla** [comment]
@hassankhan aah, too bad 😞 Hope you're getting well soon!

**Comment by vinkla** [comment]
The package is now rewritten and doesn't use the Instagram API anymore.
