### ISSUE TITLE
cURL error 60

### ISSUE THREAD

**Issue by ammaar23** [vinkla/instagram#28]
I'm using Laravel 5.1 and vinkla/instagram 4.1 and after setting up the config file and running "Instagram::users()->get(1)" I get the following error.

cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Any idea?

**Comment by vinkla** [comment]
@hassankhan any ideas?

**Comment by hassankhan** [comment]
Sounds like an issue with your environment, @ammaar23

**Comment by ammaar23** [comment]
@hassankhan I'm using OSX

**Comment by hassankhan** [comment]
Can you provide some more details? What version of PHP? How have you set it up in OSX?

**Comment by ammaar23** [comment]
I'm using any software package like xampp or mamp. I've Apache, PHP and MySQL installed separately working with each other. I've PHP 5.6.16 installed. I'm using Laravel 5.1. All I've done it follwed your installation steps.
1. Running the composer command
2. Modify config/app.php
3. Modify config/instagram.php
4 Placed "dd(Instagram::users()->get(1));" in my controller action

Below is the screenshot of the error I'm getting when I run it.

<img width="1440" alt="screen shot 2016-05-23 at 14 02 40" src="https://cloud.githubusercontent.com/assets/4119136/15471671/182eebf8-20ef-11e6-8cca-f4761b513b09.png">

**Comment by ammaar23** [comment]
Hi @hassankhan and @vinkla I've managed to resolve the issue but thank you for your support.

**Comment by rahul13bhati** [comment]
> Hi @hassankhan and @vinkla I've managed to resolve the issue but thank you for your support.

how did you managed to resolve the issue can you please explain? 
i'm facing the same issue.
