### ISSUE TITLE
ErrorException in AccessToken.php line 60:

### ISSUE THREAD

**Issue by lrpasquetto** [vinkla/instagram#29]
Hello , I can not conect to instagram

> `ErrorException in AccessToken.php line 60:`
> `Argument 1 passed to League\OAuth2\Client\Token\AccessToken::__construct() must be of the type array, null given, called in /Users/i7creative/Aplicacoes/Laravel/Noicias/vendor/larabros/elogram/src/Providers/MiddlewareServiceProvider.php on line 56 and defined`

I created the APP in Instagram developer , added the CLIENT_ID parameters , client_secret and client_token

> 'main' => [
            'id' => env('INSTAGRAN_CLIENT_ID'),
            'secret' => env('INSTAGRAN_CLIENT_SECRET'),
            'access_token' => env('INSTAGRAN_CLIENT_TOKEN'),
        ],

> public function __construct(InstagramManager $instagram){
        $this->instagram = $instagram;
        $this->instagram->connection($this->instagram->getDefaultConnection());
    }

> public function index()
    {
$response     = $this->instagram->users()->getMedia('self');
        $instagrams   = json_encode($response->get());
        dd($instagrams);
}

Can someone help me?

**Comment by sweet-greg** [comment]
I'm having the same issue

**Comment by Jojjeboy** [comment]
I'm having the same issue too.

**Comment by lukesnowden** [comment]
me too

**Comment by vinkla** [comment]
This is related to #23.

**Comment by lukesnowden** [comment]
if your just after some instagram images, just use this, no auth necessary: http://laravel.io/bin/E31k5

**Comment by vinkla** [comment]
@lukesnowden thanks for sharing!

**Comment by lukesnowden** [comment]
cant take credit for utilising the open json end point, work college sent me that, but 2 minutes for a quick Laravel class ;-)
