### ISSUE TITLE
Multiple instagram instances (receiving data of users)

### ISSUE THREAD

**Issue by Yvler** [vinkla/instagram#30]
Hi

I'm trying to get data of multiple users via a scheduler task.
When receiving the first user, everything works as planned, but when accessing the next user I get this error: "FatalThrowableError in AuthMiddleware.php line 36: Call to a member function getToken() on string"

My code:
Instagram::setAccessToken($token);
$posts = Instagram::users()->getMedia('self', 50)->get();

Is there a way to reset the Instagram / auth middleware so I can move on to the next data array?

**Comment by vinkla** [comment]
What version are you using?

**Comment by Yvler** [comment]
"vinkla/instagram": "~4.1",

**Comment by Yvler** [comment]
Any idea what I can do to prevent this ?

**Comment by vinkla** [comment]
This is related to #26
