### ISSUE TITLE
Working example missing

### ISSUE THREAD

**Issue by fabnoe** [vinkla/instagram#37]
Could you please add a working example project or controller to this repo.

**Comment by vinkla** [comment]
Please see the README file, everything you need to is added there.

**Comment by fabnoe** [comment]
I followed every single step of the Readme but Laravel shows this error:
**Class 'Vinkla\Instagram\Instagram' not found**

<?php

namespace App\Http\Controllers;

```
use App\User;
use App\Http\Controllers\Controller;
use Vinkla\Instagram\Instagram;

class TestController extends Controller
{

    public function index() {

        $instagram = new Instagram();
        $instagram->get('jerryseinfeld');


    }
```

**Comment by vinkla** [comment]
What version of the package are you using?

**Comment by fabnoe** [comment]
"vinkla/instagram": "^4.2"

**Comment by vinkla** [comment]
The README has the documentation for the latest release. You're using an older version.

**Comment by fabnoe** [comment]
Oh, that's what 'composer require vinkla/instagram' delivered

**Comment by vinkla** [comment]
You're probably using an older PHP version. The latest release is running on 7.0.

**Comment by fabnoe** [comment]
thanks. php 7 did the job

**Comment by vinkla** [comment]
:+1:
