### ISSUE TITLE
Class 'Vinkla\Instagram\InstagramServiceProvider' not found 

### ISSUE THREAD

**Issue by azizoid** [vinkla/instagram#40]
Hi, tried few times, composer update
reinstalled laravel + plugin, everytime gives the same error

[Symfony\Component\Debug\Exception\FatalThrowableError]      
  Class 'Vinkla\Instagram\InstagramServiceProvider' not found

**Comment by GrahamCampbell** [comment]
There is no service provider to register?

**Comment by GrahamCampbell** [comment]
Not since v5 anyway. If you need v4, make sure you specify the version when you require it, otherwise, composer will give you 6.x. If you're manually requiring it, make sure you never use wildcard (`*`) version constraints anywhere.

**Comment by vinkla** [comment]
@azizoid Yes, @GrahamCampbell is correct. There is no service provider anymore since we're using their open API to fetch the Instagram posts.

**Comment by azizoid** [comment]
so if there is no service provider, what you suggest to do?
coz it seems your code doesnt work out of the box.
im installing laravel, your plugin, and vuala it doesnt work
would you pls write some other HOW TO INSTALL guide? 
or im missing some part?

**Comment by vinkla** [comment]
Just because you don't know how it's works doesn't mean the package is broken. **Everything** is covered in the readme and the test have 100% coverage.

**Comment by azizoid** [comment]
it's not about me knowing how to do it
readme says nothing about service providers, 
readme says nothing about other capabilities of the package. 
just one composer code doesnt mean you explained how to use it

**Comment by GrahamCampbell** [comment]
The readme has absolutely everything in it? This package is so small. The readme is very clear and has examples covering all `1 methods in this package. Please just read the source code of you need more.

**Comment by vinkla** [comment]
> readme says nothing about service providers...

This is because there are no service provider in this package. You don't need register anything.

> readme says nothing about other capabilities of the package...

There are no other capabilities. The packages only does one thing, fetch Instagram posts.

> ...just one composer code doesnt mean you explained how to use it.

Everything you can do with the package is added to the README. As @GrahamCampbell stated, if you want to learn more, please look at the source code.
