### ISSUE TITLE
This user does not exist

### ISSUE THREAD

**Issue by manuelsofia** [vinkla/instagram#41]
Hi there,

I successfully installed the package and everything is working great except when I try to get others users data. Using the getMedia method with the default 'self' parameter will return the expected results but when I use someone else user's id I just get APINotFoundError in AbstractAdapter.php line 69: this user does not exist. This is how I'm making the call:

```
$response = Instagram::users()->getMedia('2153560316');
$instagram = json_encode($response->get()); 
```

Thanks

**Comment by vinkla** [comment]
Try using the username instead of the ID.

**Comment by manuelsofia** [comment]
@vinkla thanks a lot for the answer. It didn't work, you can only pass "self" or an id as the parameter. I think I can only make requests to other profiles while in Sandbox mode if the user has been invited and added to the sandbox. I'll check that out.

**Comment by vinkla** [comment]
Oh, we don't use the API in this library. We use their public JSON profile endpoint. Make sure the profile is public.

**Comment by manuelsofia** [comment]
Great to know, thanks. Even though all the profiles I tested are public.

**Comment by vinkla** [comment]
That is weird. Could you share some of the profiles? Then I could test it on my side and try to figure it out.

**Comment by manuelsofia** [comment]
Sure, these two are failing: 1017398766 and 2153560316

**Comment by vinkla** [comment]
Thanks, could you also share their usernames?

**Comment by manuelsofia** [comment]
djhernancattaneo for the first one, theyoungerself for the second one. Thanks for your help :)

**Comment by vinkla** [comment]
Weird, when I try them in the unit tests they work for me.

```php
$items = (new Instagram())->get('djhernancattaneo');
```

**djhernancattaneo:** https://www.instagram.com/djhernancattaneo/media/
**theyoungersel:f** https://www.instagram.com/theyoungerself/media/

**Comment by vinkla** [comment]
What version of this package are you using?

**Comment by vinkla** [comment]
From you snippet above it seems you're using an older version. Try updating to the lastest version.

**Comment by manuelsofia** [comment]
I'm using 4.1, I'll update to PHP 7 so I can run the latest version and let you know. Thanks a lot for your help :)

**Comment by manuelsofia** [comment]
FYI, I ended up updating my sever's PHP version and everything worked as expected. Thank you for your help.

**Comment by vinkla** [comment]
@manuelsofia 👍
