### ISSUE TITLE
syntax error when i call $instagram->get()

### ISSUE THREAD

**Issue by ehsand** [vinkla/instagram#42]
i get syntax error when i call get() method.
how can i fix this issue?

my code:
```
        $instagram = new Instagram();
        $instagram= $instagram->get('ehsand1986');
```

syntax error :

> FatalErrorException in Instagram.php line 55:
> syntax error, unexpected ':', expecting ';' or '{'

**Comment by vinkla** [comment]
Make sure you're running PHP 7.0 since this is required by the package.

**Comment by ehsand** [comment]
isn't work with less than php 7?

**Comment by vinkla** [comment]
No.

**Comment by nc3man** [comment]
I canNOT use php 7.0 because the primary code I'm using won't work with php 7. However, the code is so simple, you can just do a basic curl call. This worked in my case, anyway using php 5.6.29
         $ch = curl_init();
          // set URL and other appropriate options
          curl_setopt($ch, CURLOPT_URL, "https://www.instagram.com/YOUR_USER/media/");
          curl_setopt($ch, CURLOPT_HEADER, 0);
          curl_setopt($ch, CURLOPT_HTTPHEADER, array('Accept: application/json'));
          curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
          curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

          // execute curl          
          $jsonOut = curl_exec($ch);
          $data = json_decode($jsonOut, true)['items'];
