### ISSUE TITLE
Unable to install through composer Laravel 5.4.*

### ISSUE THREAD

**Issue by TobyMellor** [vinkla/instagram#43]
Using version ^4.2 for vinkla/instagram
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vinkla/instagram ^4.2 -> satisfiable by vinkla/instagram[4.2.0].
    - Conclusion: remove laravel/framework v5.4.9
    - Conclusion: don't install laravel/framework v5.4.9
    - vinkla/instagram 4.2.0 requires illuminate/session 5.1.* || 5.2.* || 5.3.* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/session v5.1.1|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.13|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.16|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.2|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.20|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.22|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.25|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.28|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.30|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.31|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.41|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.6|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.1.8|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.0|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.19|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.21|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.24|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.25|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.26|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.27|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.28|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.31|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.32|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.37|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.43|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.45|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.6|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.2.7|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.3.0|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.3.16|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.3.23|don't install laravel/framework v5.4.9
    - don't install illuminate/session v5.3.4|don't install laravel/framework v5.4.9
    - Installation request for laravel/framework (locked at v5.4.9, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.9].

Installation failed, reverting ./composer.json to its original content.

**Comment by GrahamCampbell** [comment]
> Using version ^4.2 for vinkla/instagram

You'll need a newer version of this package for that.

**Comment by vinkla** [comment]
@TobyMellor as @GrahamCampbell already noted, please use the latest version of this package.
