### ISSUE TITLE
Class 'Vinkla\Instagram\InstagramServiceProvider' not found

### ISSUE THREAD

**Issue by alamgircsejnu** [vinkla/instagram#44]
I am trying to integrate vinkla/instagram v6.0 in Laravel 5.3. But it is showing error. I tried the following steps...

1) Run "composer require vinkla/instagram" command in my application root. It worked properly.

2)Added the service provider to config/app.php in the providers array. "Vinkla\Instagram\InstagramServiceProvider::class"

and in aliases "'Instagram' => Vinkla\Instagram\Facades\Instagram::class"

3) When I run the "php artisan vendor:publish" command it shows the following error.

![instagram3](https://cloud.githubusercontent.com/assets/19221035/23093993/07b82e4a-f61b-11e6-9dba-ac0a70e995f0.PNG)

How can I solve it? Please help...

**Comment by bhargavkaklotara** [comment]
please refer the follwing post

http://www.mchampaneri.in/2017/03/debug-errors-of-external-packages-used.html

**Comment by vinkla** [comment]
@alamgircsejnu I'm guessing you've an old PHP version. Which version are you running?
