### ISSUE TITLE
Class 'Vinkla\Instagram\InstagramServiceProvider' not found with php 7

### ISSUE THREAD

**Issue by MarcosMe** [vinkla/instagram#45]
Hi, 
I'm using laravel 5.4 and php 7, but I'm still getting the error after command
php artisan vendor:publish 
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Vinkla\Instagram\InstagramServiceProvider' not found

composer require vinkla/instagram finishes ok (v6.0), but once I add the service provider
Vinkla\Instagram\InstagramServiceProvider::class I got the not found class

Do you have any idea why this is happening? Thanks

**Comment by vinkla** [comment]
In version 6.0 you don't need the service provider. We just provide a single `Instagram` class. [Please see the documentation.](https://github.com/vinkla/instagram#usage)
