### ISSUE TITLE
Full size photo

### ISSUE THREAD

**Issue by SkyZhenya** [vinkla/instagram#47]
It`s very simple package to understand how to work with it, it`s great, but how can I get full size photo from my Instagram with your package ? Or you didn`t envisage it?

**Comment by vinkla** [comment]
You can use the `standard_resolution` resolution which is the biggest they'll give you in the JSON data. Please see this JSON for reference: https://www.instagram.com/jerryseinfeld/media/

**Comment by SkyZhenya** [comment]
Max size how I can get from this lib is 640x640 in standart resolution, but it`s not a original size, it`s a square photo. If user upload in instagram not square photo (full size), and when I get it, I have this photo only 640x640, when original size is another.
For example: 
- standart_resolution: https://scontent-frx5-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/c126.0.700.700/17662040_1487571821295328_3673940897881391104_n.jpg
- original: https://scontent-frx5-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/17662040_1487571821295328_3673940897881391104_n.jpg

**Comment by vinkla** [comment]
Please see this post on StackOverflow: http://stackoverflow.com/a/31320596
