### ISSUE TITLE
what's involved in showing other people's feeds using this package?

### ISSUE THREAD

**Issue by vesper8** [vinkla/instagram#48]
Hi there, sorry if this isn't really an issue. This is the most recently updated package that came up when I searched for "Laravel Instagram" and so I'm wondering if I can use this for my specific purpose.

I'm creating a new dating website built with Laravel 5.4 and Vue 2.x. Right now my users are logging in using Socialite and Facebook.

I get that I need them to authorize my new Instagram App (created just a few days ago) before I am allowed to grab their pictures and display them on their profile with their permission.

Should I then use something like http://socialiteproviders.github.io/providers/instagram/ in order to get them to authorize my app and store the necessary tokens in my mysql database.

After which, with the token I can feed it to this package and retrieve the pictures to be displayed on their profile? I have over 100 users already and plan to have thousands within a few months.. many of which will want to connect their Instagram profiles

Would appreciate it a lot if you could tell me if this is going to work, if those are the steps I need to follow, and what I might be forgetting.

Thanks a lot!

**Comment by vinkla** [comment]
Basically, this package made for public Instagram accounts where we can fetch public JSON data. You don't need to login the user to fetch the data if the user is public. Though, if you want to fetch posts from a private user you need to log them in. Then the Socialite package will work fine to fetch an access token for the user. When you've done that you can call the Instagram API with a HTTP package such as Guzzle.
