### ISSUE TITLE
The user [username] was not found exception

### ISSUE THREAD

**Issue by chrisjohnstone** [vinkla/instagram#51]
I've recently updated my installation of WAMP to 3.0.6 (to get a more up to date version of PHP) and out of the box, the php_curl extension is enabled.

When this extension is enabled, I get an exception that the given username was not found. Disabling the extension stops the exception from occurring.

Is this to do with a conflict with Guzzle?

Laravel 5.4.21
Vinkla/Instagram 6.0

**Comment by vinkla** [comment]
What username are you testing with?

**Comment by chrisjohnstone** [comment]
I'm using my username: chrishjohnstone.

I think it might just be something to do with WAMP. I also have a mac development environment with LAMP running natively. Here I have the php_curl extension enabled in my `php.ini` and it works fine.

**Comment by vinkla** [comment]
@chrisjohnstone yeah, sounds like it could be a problem with your environment. In the next version of this package Guzzle isn't required. We'll use HTTPlug instead to let users decide what HTTP library they want.

**Comment by chrisjohnstone** [comment]
Yea, I think it must be.

I'll close this now.

**Comment by chrisjohnstone** [comment]
I was still interested in why this error was being thrown. It turns out I hadn't specified the path to `curl_cainfo` in the `php.ini`.

I got the bundle from here: http://curl.haxx.se/ca/cacert.pem and saved it in my Wamp directory.

**Comment by vinkla** [comment]
Oh, glad you solved it 👍
