### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by juanele1** [vinkla/instagram#54]
<? Php
Todos los derechos reservados
 * Este archivo es parte de Instagram.
 *
 * (C) Vincent Klaiber <hello@vinkla.com>
 *
 * Para obtener la información completa sobre derechos de autor y licencia, consulte la LICENCIA
 * Archivo que se distribuyó con este código fuente.
 * /
Declarar ( strict_types = 1 );
Namespace  Vinkla \ Instagram ;
Utilice  Http \ Client \ HttpClient ;
Utilice  Http \ Discovery \ HttpClientDiscovery ;
Utilice  Http \ Discovery \ MessageFactoryDiscovery ;
Utilice  Http \ Message \ RequestFactory ;
Todos los derechos reservados
 * Esta es la clase de instagram.
 *
* @author Vincent Klaiber <hello@vinkla.com>
 * /
Clase  Instagram
{
    Todos los derechos reservados
     * El cliente http.
     *
     * @var \ Http \ Client \ HttpClient
     * /
     $ HttpClient protegido ;
    Todos los derechos reservados
     * La fábrica de la petición del HTTP.
     *
     * @var \ Http \ Message \ RequestFactory
     * /
    protegida  $ RequestFactory ;
    Todos los derechos reservados
     * Crear una instancia de instagram nuevo.
     *
     * @param \ Http \ Client \ HttpClient | null $ httpClient
     * @param \ Http \ Message \ RequestFactory | null $ requestFactory
     *
     * @return void
     * /
    pública  función  __construct ( HttpClient  $ HttpClient  =  nula , RequestFactory  $ RequestFactory  =  nula )
    {
        $ This -> httpClient  =  $ httpClient ?: HttpClientDiscovery :: find ();
        $ This -> requestFactory  =  $ requestFactory ?: MessageFactoryDiscovery :: find ();
    }
    Todos los derechos reservados
     * Obtener los elementos multimedia.
     *
     * @param string $ user
     *
     * @throws \ Vinkla \ Instagram \ InstagramException
     *
     * @return array
     * /
    Public  function  get ( string  $ user ): array
    {
        $ Uri  =  sprintf ( ' https://www.instagram.com/%s/media/ ' , $ usuario );
        $  Request =  $ this -> requestFactory -> createRequest ( ' GET ' , $ uri );
        $  Response =  $ this -> httpClient -> sendRequest ( $ request );
        si ( $ respuesta -> getStatusCode () ===  404 ) {
            arrojar  nueva  InstagramException ( sprintf ( ' El usuario [% s] wasn \' t encontrado. ' , $ usuario ));
        }
        Return  json_decode (( string ) $ response -> getBody ()) -> elementos ;
    }
}

**Comment by vinkla** [comment]
This issue make zero sense. Please provide more information in english if you want help.
