### ISSUE TITLE
[Question] Can you fetch public posts with a certain hashtag?

### ISSUE THREAD

**Issue by zomars** [vinkla/instagram#56]

**Comment by zomars** [comment]
BTW I found that it's possible to retrieve json from a specific tags like this `https://www.instagram.com/explore/tags/example/?__a=1`.

**Comment by vinkla** [comment]
Hmm, how do you get the response in JSON?

**Comment by zomars** [comment]
I'll make a PR where I've implemented a custom method for it

**Comment by zomars** [comment]
But simply put, adding the `?__a=1` parameter makes it a JSON response.

**Comment by vinkla** [comment]
Oh, I see. I'll look into it.

**Comment by vinkla** [comment]
The output is entirely different and we only get four posts in total.

<img width="584" alt="screen shot 2017-10-18 at 7 35 43 pm" src="https://user-images.githubusercontent.com/499192/31733320-9979d868-b43b-11e7-9023-16bf04250854.png">

If you find a way to get posts by tags which has a similar output to the current setup I'm all ears. In the mean time I'll close this.
