### ISSUE TITLE
User not found error

### ISSUE THREAD

**Issue by juanpasolano** [vinkla/instagram#61]
As of today I'm getting an error no matter the username. Im sure they exists.
`PHP Fatal error:  Uncaught Vinkla\Instagram\InstagramException: The user [wondercraft_co] wasn't found. in /app/public/wp-content/themes/koko/vendor/vinkla/instagram/src/Instagram.php:74`.

PHP v 7.1.7

Maybe something changed on the Instagram side?

**Comment by vinkla** [comment]
Yes, please see #59.
