### ISSUE TITLE
Usage without SSL Certificate.

### ISSUE THREAD

**Issue by Eggotron** [vinkla/instagram#63]
Is there a way to use this package in website that don't have an SSL Certificate? I keep getting the following error but I'm not sure why:

cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I'm currently working in Local, so its a real hassle to configure all this with a SSL Certificate. Is there a way to bypass this requierement to test the functionality on local?

**Comment by vinkla** [comment]
This is not an issue with this package. I'm guessing this is something with your development environment.

**Comment by Eggotron** [comment]
It has to do with this package: php-http/guzzle6-adapter
Is it required for this to work?

**Comment by vinkla** [comment]
> Is it required for this to work?

Yes.

**Comment by Eggotron** [comment]
Ok, so is there a way for this to work on local development where it isnt required a https connection? You mentioned that its something to do with my enviroment, you mean the .env file? Is there a change I've got to make on there?

Can you please point me to some documentation about this correct configuration? It would be greatly appreciated. 

Been trying to use your package for months but haven't been able to configure it correctly and it never works for me even thought I follow the installation step by step. I don't know what I'm missing or overlooking O:
