### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Stichoza** [vinkla/instagram#64]
There's an error while fetching the media url. The URL `https://www.instagram.com/%s/media` doesn't exist for any given username.

**Comment by Stichoza** [comment]
Ok, I guess I am talking about older version.

You can get feed without access token with a bit changed URL (new rss url) `https://www.instagram.com/%s/?__a=1`

Source: https://stackoverflow.com/a/37586434/1115262 [edit]

**Comment by vinkla** [comment]
> There's an error while fetching the media url. The URL https://www.instagram.com/%s/media doesn't exist for any given username.

We've pushed an update and a new installation guide which requires an access token to be able to fetch data.

> You can get feed without access token with a bit changed URL (new rss url) https://www.instagram.com/%s/?__a=1

That URL will work but it only returns three media items.

**Comment by Stichoza** [comment]
Owkay,

P.S. returns 12 latest posts for me
