### ISSUE TITLE
incompatibility with  Latest Instagram API release

### ISSUE THREAD

**Issue by BelalAmin** [vinkla/instagram#65]
Hey there,
I tried your package but I was hit with the following error:
```php
"cURL error 6: Could not resolve host: api.instagram.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"
```
when I checked the [Latest version of Instagram API](https://www.instagram.com/developer/authentication/), I found that the authorization URL to get the access token has changed to the following : 

here is what changed: 

1. It should be POST request, not a GET
2. we need to post 4 parameters along the request which are:
     - client_id
     - client_secret_grant_type: authorization_code(currently the only supported value)
     - redirect_uri
     - code [value which we should have received prior to this request after the client authorization step]
 
```php
curl -F 'client_id=CLIENT_ID' \
    -F 'client_secret=CLIENT_SECRET' \
    -F 'grant_type=authorization_code' \
    -F 'redirect_uri=AUTHORIZATION_REDIRECT_URI' \
    -F 'code=CODE' \
    https://api.instagram.com/oauth/access_token
```

Kindly Correct me if I am missing something

**Comment by vinkla** [comment]
What version of this package are you using?

**Comment by BelalAmin** [comment]
v8

**Comment by vinkla** [comment]
I'm running the latest version and it works fine. You need to manually create the access token.
