### ISSUE TITLE
Pick photos by hashtag or from current user (not me)

### ISSUE THREAD

**Issue by ellgibug** [vinkla/instagram#66]
Hello! 
In your Instagram.php I can only find how to pick photos from myself, but I need to get pictures from 

1. other users 
2. different hashtags

Can you tell me, is this even possible?
Thanks for your package ))

**Comment by vinkla** [comment]
> Can you tell me, is this even possible?

This is currently not possible with this package. I suggest you take a look at [this package](https://github.com/mgp25/Instagram-API) instead.
