### ISSUE TITLE
Wont work on server 

### ISSUE THREAD

**Issue by adriantirusli** [vinkla/instagram#69]
When all the file is already uploaded on server, my page with the package cant be open. I try to downgrade the package but still the page wont came out and it takes too long respond but in my localhost there's no problem with that. Can you help this?

**Comment by vinkla** [comment]
You have to use the latest version since Instagram dropped the old API endpoints.

**Comment by adriantirusli** [comment]
Sorry, but previosly, i already use the latest version but the page still
the same like what ive mention

**Comment by vinkla** [comment]
Sorry, not sure what your issue is.
