### ISSUE TITLE
How can I set this up on my laravel 5 site

### ISSUE THREAD

**Issue by mdunbavan** [vinkla/instagram#7]
Hi,

I am trying to set up ,my laravel project with this but I am really finding it hard to setup:

Please can you shed some light into my setup so far as I have set the config up in the published config file but I just don't know how to get a simple feed into a page.

I keep getting this in my HomeController.php: Undefined variable: data using this setup:

```
public function index()
	{
		Instagram::setAccessToken($data);
		Instagram::connection('main')->getUserLikes();

        return view('home');


	}
```

Thanks,
Mark

**Comment by vinkla** [comment]
Hey @mdunbavan, it seems you haven't fetched the OAuth2 token in your callback. [Try reading the instructions from the base Instagram API package.](https://github.com/cosenary/Instagram-PHP-API#authenticate-user-oauth2) There you have a more detailed documentation.

**Comment by mdunbavan** [comment]
Hey @vinkla I followed this but its still giving me "Undefined index: code" when I do:

```
$code = $_GET['code'];
    $data = $instagram->getOAuthToken($code);
    Instagram::setAccessToken($data);

    echo 'Your username is: ' . $data->user->username;
    Instagram::connection('main')->getUserLikes();
```

**Comment by vinkla** [comment]
Have you added the correct callback URL to your instagram application?

**Comment by mdunbavan** [comment]
Hey @vinkla yeah its http://borough.cc and when I manage clients I can see it here:

CLIENT ID	******************************
CLIENT SECRET	*****************************
WEBSITE URL	http://borough.cc
REDIRECT URL	http://borough.cc

**Comment by vinkla** [comment]
Great. Could you provide your routes and the controller as well?

**Comment by mdunbavan** [comment]
routes:

```
Route::get('/', 'HomeController@index');
```

HomeController.php:

```
<?php namespace App\Http\Controllers;

class HomeController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Home Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders your application's "dashboard" for users that
	| are authenticated. Of course, you are free to change or remove the
	| controller as you wish. It is just here to get your app started!
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */public function index()
	{

	$code = $_GET['code'];
    $data = $instagram->getOAuthToken($code);
    Instagram::setAccessToken($data);

    echo 'Your username is: ' . $data->user->username;
    Instagram::connection('main')->getUserLikes();

        return view('home');


	}


}
```

composer.json:

```
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.0.*",
		"illuminate/html": "5.*",
		"vinkla/instagram": "~2.0"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1"
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	}
}
```

**Comment by vinkla** [comment]
Do you want the user to login or just to fetch data from the Instagram API?

**Comment by mdunbavan** [comment]
Just fetch data from Instagram

**Comment by mdunbavan** [comment]
In the old Cosenary one I did I just used this:

```
$name = 'borough_cc';
$result = $instagram->getTagMedia($name, 3);
```

**Comment by vinkla** [comment]
Then you wont need to fetch the token. You can just fetch the feed with a name. Try as in the [dependency injection example](https://github.com/vinkla/instagram#examples) instead.

```php
<?php namespace App\Http\Controllers;

use Vinkla\Instagram\InstagramManager;

class HomeController extends Controller {

	/**
	 * @var InstagramManager
	 */
	private $instagramManager;

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct(InstagramManager $instagramManager)
	{
		$this->instagramManager = $instagramManager;
		$this->middleware('auth');
	}

	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		$name = 'borough_cc';
		$result = $this->instagramManager->getTagMedia($name, 3);

		return view('home');
	}

}

```

**Comment by mdunbavan** [comment]
oh cool thats great cheers @vinkla just one more thing is it possible to use this in it too?

```
foreach ($result->data as $media) {
	            $content = "<li class='col-1-3'>";
	            
	            // output media
	            if ($media->type === 'video') {
	              // video
	              $poster = $media->images->standard_resolution->url;
	              $source = $media->videos->standard_resolution->url;
	              $content .= "<video class=\"media video-js vjs-default-skin\" width=\"250\" height=\"250\" poster=\"{$poster}\"
	                           data-setup='{\"controls\":true, \"preload\": \"auto\"}'>
	                             <source src=\"{$source}\" type=\"video/mp4\" />
	                           </video>";
	            } else {
	              // image
	              $image = $media->images->standard_resolution->url;
	              $content .= "<img class=\"media\" src=\"{$image}\"/>";
	            }
	            
	            // create meta section
	            $avatar = $media->user->profile_picture;
	            $username = $media->user->username;
	            $comment = $media->caption->text;
	            $content .= "<div class=\"content\">
	                           <div class=\"avatar\" style=\"background-image: url({$avatar})\"></div>
	                           <h3>{$username}</h3>
	                           <div class=\"comment\"><p>{$comment}</p></div>
	                         </div>";
	            
	            // output media
	            echo $content . "</li>";
	          }
```

**Comment by vinkla** [comment]
Yes this is possible. Return the `$result` variable to your view.

```php

/**
 * Show the application dashboard to the user.
 *
 * @return Response
 */
public function index()
{
	$name = 'borough_cc';
	$result = $this->instagramManager->getTagMedia($name, 3);

        return view('home', compact('result'));
}
```

**Comment by mdunbavan** [comment]
its okay fixed now, just did this:

```
->with('result', $result);
```

Thanks @vinkla that worked a treat :)

**Comment by vinkla** [comment]
Great!

**Comment by puzpuz** [comment]
Hi vinkla, I'm new to laravel, and I would like to try your Instagram wrapper and follow the above but I get this following error
>Call to a member function getTagMedia() on a non-object

this is the syntax that I used

    protected $instagram;
    public function _construct(InstagramManager $instagramManager) {
        $this->instagram = $instagramManager;
    }
    public function index() {
        $userId = 'sby.sweetrecipe';
        $result  = $this->instagram->getTagMedia($userId,30);
    }

Please help me, thank you

**Comment by vinkla** [comment]
Did you import the `InstagramManager` at the top?

**Comment by puzpuz** [comment]
Hi, I already import it here
<pre><code>use Vinkla\Instagram\InstagramManager;</code></pre>

And already set the service provider
<pre><code> Vinkla\Instagram\InstagramServiceProvider::class,</code></pre>

And even though I have define a Facade for <code>Instagram</code>, every time I call <code>Instagram::{method_name}</code>, the method is always undefined

**Comment by vinkla** [comment]
Could you paste your `composer.json` file conents?

**Comment by puzpuz** [comment]
thank you for your awesome support, this is my composer.json

	{
		"name": "laravel/laravel",
		"description": "The Laravel Framework.",
		"keywords": ["framework", "laravel"],
		"license": "MIT",
		"type": "project",
		"require": {
			"php": ">=5.5.9",
			"laravel/framework": "5.1.*",
			"vinkla/instagram": "^3.1"
		},
		"require-dev": {
			"fzaninotto/faker": "~1.4",
			"mockery/mockery": "0.9.*",
			"phpunit/phpunit": "~4.0",
			"phpspec/phpspec": "~2.1"
		},
		"autoload": {
			"classmap": [
				"database"
			],
			"psr-4": {
				"App\\": "app/"
			}
		},
		"autoload-dev": {
			"classmap": [
				"tests/TestCase.php"
			]
		},
		"scripts": {
			"post-install-cmd": [
				"php artisan clear-compiled",
				"php artisan optimize"
			],
			"pre-update-cmd": [
				"php artisan clear-compiled"
			],
			"post-update-cmd": [
				"php artisan optimize"
			],
			"post-root-package-install": [
				"php -r \"copy('.env.example', '.env');\""
			],
			"post-create-project-cmd": [
				"php artisan key:generate"
			]
		},
		"config": {
			"preferred-install": "dist"
		}
	}
	
So after I create new laravel project, I run composer <code>composer require vinkla/instagram</code>, put the service provider and facade on <code>app.php</code>
Then, I publish it first to generate <code>instagram.php</code> and setup my connection there, am I missing something?

**Comment by vinkla** [comment]
No, everything seems to be in order. This is very strange. Try doing a fresh install. Remove `vendor` and reinstall with `composer install`. I'm just guessing now. Your setup seems fine …

**Comment by puzpuz** [comment]
I have re-create the project from scratch, re-install laravel project using composer and add the instagram wrapper again, but still no luck. I'm using XAMPP as local server and not using Homestead, maybe that's affecting something?

I do some searching and I found on vendor/cosenary/src/instagram.php, there is a method called <code>getTagMedia($name,$limit = 0)</code> this one is from instagram php API I believe, but I don't know why I can't call the method from InstagramManager

**Comment by vinkla** [comment]
This is very strange.
