### ISSUE TITLE
Type error: Argument 1 passed to Vinkla\Instagram\Instagram::__construct() must be an instance of Http\Client\HttpClient or null, string given

### ISSUE THREAD

**Issue by lukehatfield** [vinkla/instagram#72]
I get the above error when trying to pass an access token to the library. Here's the line that is causing the error to show (access token changed for question):
`$instagram = new Instagram('2031234818.1612ok3.867bdc1cd12l44321c7f43a12be74edb');`. Am I breaking something obvious?

![screenshot 2018-03-09 17 21 57](https://user-images.githubusercontent.com/5399943/37232890-ec3d5bfe-23be-11e8-8e5c-ac1f0841d52b.png)

**Comment by vinkla** [comment]
Hmm, that seems odd. Please show me the row 54 from the `InstagramTags` class.

**Comment by vinkla** [comment]
What version of the package are you using? It is not longer possible to send a username as an argument to the `get()` method:

https://github.com/vinkla/instagram/blob/317f07426b233e3ed4bf791474b172bc5df2509d/src/Instagram.php#L72

**Comment by lukehatfield** [comment]
Sorry @vinkla, I messed that screenshot up. It was line 53 in the screenshot, pasting the code here:
```
$instagram = new Instagram('2031234818.1612ok3.867bdc1cd12l44321c7f43a12be74edb');
```
I removed the username and still ended up with the error (this time on that line 53). I think I'm on version 8.0. I have the following in my `composer.json`:
```
"require": {
        "vinkla/instagram": "^8.0",
```

**Comment by vinkla** [comment]
Did you install the HTTPlug libraries?

```sh
$ composer require vinkla/instagram php-http/message php-http/guzzle6-adapter
```

**Comment by lukehatfield** [comment]
yes, I have those in there as well. Here's the rest of my composer.json. But I'm working in the Statamic CMS and constructing this as an add-on. Something must just not be connecting right.
```

**Comment by vinkla** [comment]
> Something must just not be connecting right.

TBH I'm sorry but I've no idea what is going on. Did you accidentally update the `Instagram` class within the package? Did you try to remove the `vendor` directory and reinstall the packages?

**Comment by lukehatfield** [comment]
Must be something like that. I'll keep tinkering with it. Thanks again for the awesome plugin!

**Comment by vinkla** [comment]
I'm glad you like it. Please let me know if you find anything!

**Comment by lukehatfield** [comment]
It turns out there was a `composer.lock`file higher up in the Statamic CMS structure that was preventing the package from updating to v8.0.0, and kept it at v7. Once I figured out how to update the CMS, that lock file was also updated and all works now! Thanks again for your help.

**Comment by vinkla** [comment]
Oh, okay. Glad you solved it. I’ll close this now.

**Comment by edalzell** [comment]
@lukehatfield how did you do this, I have the same problem.
