### ISSUE TITLE
Undefined property: stdClass::$data 

### ISSUE THREAD

**Issue by prajapatim** [vinkla/instagram#74]
I have found this issue. I am sharing a screenshot.

![screenshot-2018-5-3 whoops there was an error](https://user-images.githubusercontent.com/20574576/39569234-3bf9731e-4ee2-11e8-9bf6-c59d4c014b93.png)

**Comment by vinkla** [comment]
Thanks for reporting! Please share the JSON object from `$response->getBody()`.

**Comment by bantawa04** [comment]
I'm also having the same issue on my site.

**Comment by vinkla** [comment]
This is fixed in ca25c21855396c3ad9e26e30b2c6556586b0ec93.
