### ISSUE TITLE
get somebody information

### ISSUE THREAD

**Issue by MahdiPishguy** [vinkla/instagram#77]
how can i get somebody users information?

by `self()` i can get my own info but i want to get other users information

for example:
```
$instagram = new Instagram('MY_TOKEN');  //   http://instagram.pixelunion.net
$output = $instagram->get('insta__cheeta');
```

**Comment by vinkla** [comment]
Hey @MahdiPishguy, you'll have to obtain a new access token for that specific user if you want to fetch information from another user.
