### ISSUE TITLE
Undefined property: stdClass::$data

### ISSUE THREAD

**Issue by nicolascarelli** [vinkla/instagram#78]
Hi,

Thanks for your great tool!
I ve made it work ok in dev
http://dev.7mar.com.ar/admin_new/api/instagram

And prod too.
But now in prod it is failing.
https://7mar.com.ar/admin_new/api/instagram
<img width="1280" alt="captura de pantalla 2018-06-08 a la s 10 18 24" src="https://user-images.githubusercontent.com/14168144/41160437-1e25f408-6b06-11e8-976d-b5b5e8201a5a.png">

**Comment by vinkla** [comment]
Try updating to the latest version.

**Comment by nicolascarelli** [comment]
it is working now, again; by itself
thanks
