### ISSUE TITLE
Error of Undefined property: stdClass::$data 

### ISSUE THREAD

**Issue by bantawa04** [vinkla/instagram#79]
Updated the package to it's latest  9.0.0 and still getting error with message 

> Undefined property: stdClass::$data 

![1](https://user-images.githubusercontent.com/22129795/41216561-945ae460-6d74-11e8-98a9-f0f5df576ab4.PNG)

My code for getting the feed
`    public function instagramFeed(View $view)
    {
      $instagram = new \Vinkla\Instagram\Instagram('my-access-token');
      $feed      = $instagram->media();
      $view->withFeeds($feed);
    }`

**Comment by bantawa04** [comment]
Sometimes it works fine and sometimes it doesn't leaving the whole site broken as I've included instagram feeds in footers section of my site.

**Comment by vinkla** [comment]
This could be rate limiting:

> _The Instagram API uses the same rate limiting as the Graph API (200 calls per user per hour) with one exception: the /media/comments edge limits writes to 60 writes per user per hour. Please refer to the Graph API's rate limiting documentation for more information_ - [Facebook](https://developers.facebook.com/docs/instagram-api/overview/#rate-limiting)

Do you cache the media items in your application or do you always fetch from Instagram?

**Comment by vinkla** [comment]
I've pushed an update which catches the rate limit error message in version [9.0.1](https://github.com/vinkla/instagram/releases/tag/9.0.1).
