### ISSUE TITLE
How to initialize?

### ISSUE THREAD

**Issue by sophiekovalevsky** [vinkla/instagram#8]
Hi:

There is a problem when I try to use the API because when I use this: Instagram::setAccessToken($data); 

Laravel tells me that data variables is not defined. What I'm doing wrong?

**Comment by sophiekovalevsky** [comment]
I got it now.

**Comment by vinkla** [comment]
Good you solved it!

**Comment by rex** [comment]
So for the rest of us that haven't got the first clue about where the `$data` comes from in `setAccessToken::($data)`, it would be *extremely* helpful if you would post your solution to the issue, @sophiekovalevsky

**Comment by sophiekovalevsky** [comment]
Rex, actually now that you came with that question, I'm gonna try to make a pull request to generate an example in the doc. I hope that vinkla could accept it to help others that stuck with the same issue :D.

**Comment by vinkla** [comment]
Hey guys, thanks for reaching out. The update has been merged in #11

**Comment by rex** [comment]
@sophiekovalevsky Thank you for that! You rock! 

I suppose I am a bit disappointed that this library doesn't handle the Oauth dance on its own. I'm sure this works great for apps that work on behalf of other users who have to manually handle the Oauth authentication flow but I only need to retrieve my own information. I'm going to see if I can generate the token somehow so I can use this library but I might just making `GET` calls to their public api and be done with it.
