### ISSUE TITLE
Return value of Vinkla\Instagram\Instagram::get() must be an instance of Vinkla\Instagram\object, instance of stdClass returned

### ISSUE THREAD

**Issue by techn0guy** [vinkla/instagram#81]
Hello I am receiving this error: "Type error: Return value of Vinkla\Instagram\Instagram::get() must be an instance of Vinkla\Instagram\object, instance of stdClass returned" when trying to fetch the Instagram media. I have downloaded the latest version.

The issue seems to go away when I remove ```: object``` from ```protected function get(string $path): object```

**Comment by vinkla** [comment]
Try updating to the latest version of this package and PHP and see if that helps.

**Comment by julianchristmas** [comment]
If this issue persist, try run ``` php -v ``` from CLI
If you are below PHP v. 7.2 this is the reason.
