### ISSUE TITLE
get() must be an instance of Vinkla\Instagram\object, instance of stdClass returned

### ISSUE THREAD

**Issue by MichaelHoughton** [vinkla/instagram#82]
I just installed your package on a new Laravel 5.6.24 installation.

The code I have is:

```php
$instagram = new Instagram('token');
dd($instagram->media());
```
It is throwing the following error:

```php
Return value of Vinkla\Instagram\Instagram::get() must be an instance of Vinkla\Instagram\object, instance of stdClass returned
```

Screen shot below:
![screenshot at 2018-06-28 13-09-40](https://user-images.githubusercontent.com/5341149/42033427-c3830d04-7ad4-11e8-9c1e-cdc56b322859.png)

Please let me know if you might know what is causing this.

**Comment by vinkla** [comment]
Try updating to PHP 7.2+

**Comment by sjopet** [comment]
try fixing your composer requirements tbh

**Comment by tobiushirogeri** [comment]
I'm facing the same issue with php 7.2.9 and Laravel Framework 5.6.26


```
 $instagram = new Instagram(config('instagram.token'));
        $instagram->media();

```

"Return value of Vinkla\Instagram\Instagram::get() must be an instance of Vinkla\Instagram\object, instance of stdClass returned"

**Comment by vinkla** [comment]
> Return value of Vinkla\Instagram\Instagram::get() must be an instance of Vinkla\Instagram\object, instance of stdClass returned

Try updating to PHP 7.2+

**Comment by tobiushirogeri** [comment]
@vinkla  I actually am using php 7.2.9....
