### ISSUE TITLE
More structure to the response data

### ISSUE THREAD

**Issue by Rezrazi** [vinkla/instagram#84]
Hey,

I was just wondering if there's a way to get a more structured response, instead of the plain json data, for example creating an instance of an Instagram profile, which would hold different methods and attributes.
If there's an already available package for that, can you please provide a name, writing this from scratch would be possible, but this a small part of a bigger project, and we're trying to manage resources.

Best regards.

**Comment by vinkla** [comment]
I’ll look at any pull request you send my way.
