### ISSUE TITLE
media method not work

### ISSUE THREAD

**Issue by vahidalvandi** [vinkla/instagram#85]
$insta = new Instagram();

   $getUser = $insta->get('gopro');

   dd($getUser);

**Comment by vinkla** [comment]
Hmm, it looks like you're using an older version of the package. Try updating the package and update the `get` method call to `media`.

**Comment by vahidalvandi** [comment]
no i run composer install like readme.md in this repo

**Comment by vinkla** [comment]
In your example you're using `get` instead of `media`. Try switching.

**Comment by vahidalvandi** [comment]
media not found in last version

**Comment by vinkla** [comment]
It is found here:

https://github.com/vinkla/instagram/blob/33674990c5ae0c08d6e321671a0ed85b048d100e/src/Instagram.php#L77-L82

As I've previously said, you're probably using an older version of the package.

**Comment by vahidalvandi** [comment]
i will test it later
