### ISSUE TITLE
Call to undefined method Vinkla\Instagram\Instagram::self()

### ISSUE THREAD

**Issue by SebastianCBA** [vinkla/instagram#86]
Hi, I just installed the package and when executing the following lines

>     $instagram = new Instagram('Token_by_Union_Pixel');
>     $instagram->self();

I get this error:

(1/1) FatalThrowableErrorCall to undefined method Vinkla\Instagram\Instagram::self()

Can you help me?
Thanks in advance! Regards

**Comment by vinkla** [comment]
It looks like you're running an older version of this package. Make sure you've installed PHP 7.2+ and run `composer update` to get the latest version of this package.

**Comment by SebastianCBA** [comment]
I have PHP 7.1 installed, does not work with this version?

**Comment by vinkla** [comment]
> I have PHP 7.1 installed, does not work with this version?

No, make sure you've installed PHP 7.2+.

**Comment by SebastianCBA** [comment]
Hi vinkla, I was installed PHP 7.2.9 and this wotk correctly, Thanks!

How I can get posts or media from an other users like http://www.twitter.com/maluma ?

**Comment by vinkla** [comment]
> How I can get posts or media from an other users like http://www.twitter.com/maluma ?

You can't if you don't have their access token.
