### ISSUE TITLE
Version confusion 

### ISSUE THREAD

**Issue by jdsingh** [vinkla/instagram#9]
Please specify in docs that this package is compatible with "version" of Laravel.

I'm using laravel 4.2 for my project. 

You specified that one should install v1.0 for Laravel 4. Where can I find docs for that?

Thanks for your help.

**Comment by GrahamCampbell** [comment]
https://github.com/vinkla/instagram/tree/1.0.1

**Comment by GrahamCampbell** [comment]
> Please specify in docs that this package is compatible with "version" of Laravel.

Why is that needed. The composer.json file documents that. Anyway, if it's installable, by definition, it's compatible. If composer throws a wobbly when you install it, you've got the wrong version.

**Comment by jdsingh** [comment]
@GrahamCampbell thanks for quick reply.

It would be nice to have written in readme that its a Laravel 5 package. It makes things more clear for developers like me. 

Here is a good example: [LaravelFacebookSdk](https://github.com/SammyK/LaravelFacebookSdk)

**Comment by vinkla** [comment]
Added in https://github.com/vinkla/instagram/commit/b4a25b319da7131ef62192592153b00f899f353e. Thanks.
