### ISSUE TITLE
Feed limit

### ISSUE THREAD

**Issue by uiina** [vinkla/instagram#90]
Can someone tell me how to limit the feed?
Here is my code

$instagram = new Instagram(config('services.instagram.access-token'));
$images = collect($instagram->media())->map(function ($each) {
          return $each->images->low_resolution->url;
});

Thank you

**Comment by vinkla** [comment]
It looks like you're using Laravel collection, then you may use the [`take`](https://laravel.com/docs/5.7/collections#method-take) method:
```php
$images = collect($images)->take(5);
```
