### ISSUE TITLE
Vinkla/Instagram

### ISSUE THREAD

**Issue by 161710101** [vinkla/instagram#94]
![image](https://user-images.githubusercontent.com/33051606/47418129-b3253000-d7a3-11e8-85bb-eb910bbfea32.png)

**Comment by vinkla** [comment]
> _When a person reviews an Issue Request there should be enough information that they have a good handle of what is being discussed, they don’t need to know or come up with a solution instantly, but nothing about the issue should be mystery meat - [UpThemes](https://upthemes.com/blog/2014/02/writing-useful-github-issues/)_

You're probably using an old version of the package.
