### ISSUE TITLE
how can i use all endpoints  available in www.instagram.com/developer/endpoints/?

### ISSUE THREAD

**Issue by yeisonramirez** [vinkla/instagram#96]

**Comment by vinkla** [comment]
> _When a person reviews an Issue Request there should be enough information that they have a good handle of what is being discussed, they don’t need to know or come up with a solution instantly, but nothing about the issue should be mystery meat - [UpThemes](https://upthemes.com/blog/2014/02/writing-useful-github-issues/)_
