### ISSUE TITLE
Instagram API Platform Going To Deprecate

### ISSUE THREAD

**Issue by djneo92nl** [vinkla/instagram#97]
Hello,

will this package continou working after the Instagram removes there public api's 
https://www.instagram.com/developer/
https://developers.facebook.com/blog/post/2018/01/30/instagram-graph-api-updates/

**Comment by vinkla** [comment]
Hey @djneo92nl, thanks for reaching out! I haven't heard about this before.

The [changelog](https://developers.facebook.com/blog/post/2018/01/30/instagram-graph-api-updates/) states the following:

- **Public Content** - all remaining capabilities to read public media on a user's behalf on 
December 11, 2018.
- **Basic** - to read a user’s own profile info and media in early 2020.

I'm not sure if this package will be affected by the new changes or if we can continue using this setup until 2020.

**Comment by djneo92nl** [comment]
Hy, thanks for the fast response.

My idea is that the package only uses Basic information, i'm retrieving only my own images

**Comment by vinkla** [comment]
> My idea is that the package only uses Basic information, i'm retrieving only my own images

Yes, I hope that is the case as well. Let's see what happens on December 11-12. I'll look into it if it stops to work.

**Comment by djneo92nl** [comment]
hey, 

i tested my script and everything worked fine :D

**Comment by vinkla** [comment]
Great! Then I'll go ahead and close this.
